# Generated by Django 6.0.4 on 2026-05-31 03:21

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_mfa_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.avatar_upload_path),
        ),
    ]
