/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as Home_pageRouteImport } from './routes/home_page'
import { Route as Favorite_pageRouteImport } from './routes/favorite_page'
import { Route as Cart_pageRouteImport } from './routes/cart_page'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIdRouteImport } from './routes/seller/$id'
import { Route as ProductIdRouteImport } from './routes/product/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const Home_pageRoute = Home_pageRouteImport.update({
  id: '/home_page',
  path: '/home_page',
  getParentRoute: () => rootRouteImport,
} as any)
const Favorite_pageRoute = Favorite_pageRouteImport.update({
  id: '/favorite_page',
  path: '/favorite_page',
  getParentRoute: () => rootRouteImport,
} as any)
const Cart_pageRoute = Cart_pageRouteImport.update({
  id: '/cart_page',
  path: '/cart_page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart_page': typeof Cart_pageRoute
  '/favorite_page': typeof Favorite_pageRoute
  '/home_page': typeof Home_pageRoute
  '/register': typeof RegisterRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart_page': typeof Cart_pageRoute
  '/favorite_page': typeof Favorite_pageRoute
  '/home_page': typeof Home_pageRoute
  '/register': typeof RegisterRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart_page': typeof Cart_pageRoute
  '/favorite_page': typeof Favorite_pageRoute
  '/home_page': typeof Home_pageRoute
  '/register': typeof RegisterRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart_page'
    | '/favorite_page'
    | '/home_page'
    | '/register'
    | '/product/$id'
    | '/seller/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart_page'
    | '/favorite_page'
    | '/home_page'
    | '/register'
    | '/product/$id'
    | '/seller/$id'
  id:
    | '__root__'
    | '/'
    | '/cart_page'
    | '/favorite_page'
    | '/home_page'
    | '/register'
    | '/product/$id'
    | '/seller/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Cart_pageRoute: typeof Cart_pageRoute
  Favorite_pageRoute: typeof Favorite_pageRoute
  Home_pageRoute: typeof Home_pageRoute
  RegisterRoute: typeof RegisterRoute
  ProductIdRoute: typeof ProductIdRoute
  SellerIdRoute: typeof SellerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home_page': {
      id: '/home_page'
      path: '/home_page'
      fullPath: '/home_page'
      preLoaderRoute: typeof Home_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite_page': {
      id: '/favorite_page'
      path: '/favorite_page'
      fullPath: '/favorite_page'
      preLoaderRoute: typeof Favorite_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart_page': {
      id: '/cart_page'
      path: '/cart_page'
      fullPath: '/cart_page'
      preLoaderRoute: typeof Cart_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Cart_pageRoute: Cart_pageRoute,
  Favorite_pageRoute: Favorite_pageRoute,
  Home_pageRoute: Home_pageRoute,
  RegisterRoute: RegisterRoute,
  ProductIdRoute: ProductIdRoute,
  SellerIdRoute: SellerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
