/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Success_pageRouteImport } from './routes/success_page'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as My_account_pageRouteImport } from './routes/my_account_page'
import { Route as Home_pageRouteImport } from './routes/home_page'
import { Route as Favorite_pageRouteImport } from './routes/favorite_page'
import { Route as Contact_pageRouteImport } from './routes/contact_page'
import { Route as Cart_pageRouteImport } from './routes/cart_page'
import { Route as Cancel_pageRouteImport } from './routes/cancel_page'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIdRouteImport } from './routes/seller/$id'
import { Route as ProductIdRouteImport } from './routes/product/$id'

const Success_pageRoute = Success_pageRouteImport.update({
  id: '/success_page',
  path: '/success_page',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const My_account_pageRoute = My_account_pageRouteImport.update({
  id: '/my_account_page',
  path: '/my_account_page',
  getParentRoute: () => rootRouteImport,
} as any)
const Home_pageRoute = Home_pageRouteImport.update({
  id: '/home_page',
  path: '/home_page',
  getParentRoute: () => rootRouteImport,
} as any)
const Favorite_pageRoute = Favorite_pageRouteImport.update({
  id: '/favorite_page',
  path: '/favorite_page',
  getParentRoute: () => rootRouteImport,
} as any)
const Contact_pageRoute = Contact_pageRouteImport.update({
  id: '/contact_page',
  path: '/contact_page',
  getParentRoute: () => rootRouteImport,
} as any)
const Cart_pageRoute = Cart_pageRouteImport.update({
  id: '/cart_page',
  path: '/cart_page',
  getParentRoute: () => rootRouteImport,
} as any)
const Cancel_pageRoute = Cancel_pageRouteImport.update({
  id: '/cancel_page',
  path: '/cancel_page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancel_page': typeof Cancel_pageRoute
  '/cart_page': typeof Cart_pageRoute
  '/contact_page': typeof Contact_pageRoute
  '/favorite_page': typeof Favorite_pageRoute
  '/home_page': typeof Home_pageRoute
  '/my_account_page': typeof My_account_pageRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/success_page': typeof Success_pageRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancel_page': typeof Cancel_pageRoute
  '/cart_page': typeof Cart_pageRoute
  '/contact_page': typeof Contact_pageRoute
  '/favorite_page': typeof Favorite_pageRoute
  '/home_page': typeof Home_pageRoute
  '/my_account_page': typeof My_account_pageRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/success_page': typeof Success_pageRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cancel_page': typeof Cancel_pageRoute
  '/cart_page': typeof Cart_pageRoute
  '/contact_page': typeof Contact_pageRoute
  '/favorite_page': typeof Favorite_pageRoute
  '/home_page': typeof Home_pageRoute
  '/my_account_page': typeof My_account_pageRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/success_page': typeof Success_pageRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cancel_page'
    | '/cart_page'
    | '/contact_page'
    | '/favorite_page'
    | '/home_page'
    | '/my_account_page'
    | '/payment'
    | '/register'
    | '/success_page'
    | '/product/$id'
    | '/seller/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cancel_page'
    | '/cart_page'
    | '/contact_page'
    | '/favorite_page'
    | '/home_page'
    | '/my_account_page'
    | '/payment'
    | '/register'
    | '/success_page'
    | '/product/$id'
    | '/seller/$id'
  id:
    | '__root__'
    | '/'
    | '/cancel_page'
    | '/cart_page'
    | '/contact_page'
    | '/favorite_page'
    | '/home_page'
    | '/my_account_page'
    | '/payment'
    | '/register'
    | '/success_page'
    | '/product/$id'
    | '/seller/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Cancel_pageRoute: typeof Cancel_pageRoute
  Cart_pageRoute: typeof Cart_pageRoute
  Contact_pageRoute: typeof Contact_pageRoute
  Favorite_pageRoute: typeof Favorite_pageRoute
  Home_pageRoute: typeof Home_pageRoute
  My_account_pageRoute: typeof My_account_pageRoute
  PaymentRoute: typeof PaymentRoute
  RegisterRoute: typeof RegisterRoute
  Success_pageRoute: typeof Success_pageRoute
  ProductIdRoute: typeof ProductIdRoute
  SellerIdRoute: typeof SellerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success_page': {
      id: '/success_page'
      path: '/success_page'
      fullPath: '/success_page'
      preLoaderRoute: typeof Success_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my_account_page': {
      id: '/my_account_page'
      path: '/my_account_page'
      fullPath: '/my_account_page'
      preLoaderRoute: typeof My_account_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home_page': {
      id: '/home_page'
      path: '/home_page'
      fullPath: '/home_page'
      preLoaderRoute: typeof Home_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite_page': {
      id: '/favorite_page'
      path: '/favorite_page'
      fullPath: '/favorite_page'
      preLoaderRoute: typeof Favorite_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact_page': {
      id: '/contact_page'
      path: '/contact_page'
      fullPath: '/contact_page'
      preLoaderRoute: typeof Contact_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart_page': {
      id: '/cart_page'
      path: '/cart_page'
      fullPath: '/cart_page'
      preLoaderRoute: typeof Cart_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel_page': {
      id: '/cancel_page'
      path: '/cancel_page'
      fullPath: '/cancel_page'
      preLoaderRoute: typeof Cancel_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Cancel_pageRoute: Cancel_pageRoute,
  Cart_pageRoute: Cart_pageRoute,
  Contact_pageRoute: Contact_pageRoute,
  Favorite_pageRoute: Favorite_pageRoute,
  Home_pageRoute: Home_pageRoute,
  My_account_pageRoute: My_account_pageRoute,
  PaymentRoute: PaymentRoute,
  RegisterRoute: RegisterRoute,
  Success_pageRoute: Success_pageRoute,
  ProductIdRoute: ProductIdRoute,
  SellerIdRoute: SellerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
