# Generated by Django 6.0.4 on 2026-04-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='place_holder_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
