// Generated by i18next-cli — review and adapt to your project's needs.
// You may need to install dependencies: npm install i18next react-i18next i18next-resources-to-backend
//
// Other translation loading approaches:
//   • Static imports or bundled JSON: https://www.i18next.com/how-to/add-or-load-translations
//   • Lazy-load from a server: https://github.com/i18next/i18next-http-backend
//   • Manage translations with your team via Locize: https://www.locize.com
//     (see i18next-locize-backend: https://github.com/locize/i18next-locize-backend)
import i18next from 'i18next'
import { initReactI18next } from 'react-i18next'
import resourcesToBackend from 'i18next-resources-to-backend'
import LanguageDetector from "i18next-browser-languagedetector"

i18next
  .use(LanguageDetector)
  .use(initReactI18next)
  .use(resourcesToBackend((language, namespace) => import(`./locales/${language}/${namespace}.json`)))
  .init({
    returnEmptyString: false, // allows empty string as valid translation
    // lng: 'vn', // or add a language detector to detect the preferred language of your user
    fallbackLng: 'en',
    defaultNS: 'translation',
  })

export default i18next
