# Generated by Django 6.0.4 on 2026-05-30 05:12

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_place_holder_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='place_holder_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.user_upload_path),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
